Added missing Validator trait to EditorHelper
```
error[E0277]: the trait bound `editor::EditorHelper: rustyline::validate::Validator` is not satisfied
   --> src/editor.rs:194:6
    |
194 | impl Helper for EditorHelper {}
    |      ^^^^^^ the trait `rustyline::validate::Validator` is not implemented for `editor::EditorHelper`
    |
   ::: /Users/netrom/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-6.2.0/src/lib.rs:728:46
    |
728 |     Self: Completer + Hinter + Highlighter + Validator,
    |                                              --------- required by this bound in `rustyline::Helper`
```